modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (31 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="endreborn" #mandatory
version="0.7.0" #mandatory
displayName="End: Reborn" #mandatory
updateJSONURL="https://github.com/EleC0TroN/ER" #optional
displayURL="https://github.com/EleC0TroN/ER" #optional
logoFile="logo.png" #optional
credits="Mod for MC." #optional
authors="EleC0TroN" #optional
description="The dragon was only the beginning. And The End more than your brain can imagine"
[[dependencies.endreborn]] #optional
    modId="forge" 
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.endreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
