modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="endreborn" #mandatory
version="0.5.2" #mandatory
displayName="End: Reborn" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="Mod for MC." #optional
authors="EleC0TroN" #optional
description="The dragon was only the beginning. And the End more than your brain can imagine"
[[dependencies.endreborn]] #optional
    modId="forge" 
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.endreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
